import { useState } from 'react'
import CallTree from '../visualizations/CallTree.jsx'
import CodeEditor from '../python/CodeEditor.jsx'
import AnswerField from './AnswerField.jsx'

export default function Memoization({ answers, onChange, code, onCode, record, onBusyChange }) {
  const [comparison, setComparison] = useState(false)
  return <>
    <section className="activity-section"><p className="eyebrow">Activity 1 · Diagnose wasted work</p><h3>Same input, same computation</h3><p>Inspect the naive call tree. Click a node to highlight every call with that input. Count how often <code>fib(2)</code> appears, then explain how much of that work is repeated.</p><CallTree record={record} /><div className="prediction-fields"><div><label htmlFor="repeated-count">Number of fib(2) calls</label><input id="repeated-count" type="number" min="0" value={answers['repeated-count'] ?? ''} onChange={(event) => onChange('repeated-count', event.target.value)} /></div></div><AnswerField id="redundancy-explanation" label="Why is recomputing an identical input unnecessary?" value={answers['redundancy-explanation']} onChange={onChange} /></section>
    <section className="activity-section"><p className="eyebrow">Activity 2 · Refactor with a cache</p><h3>Keep the result, skip the repeated branch</h3><p>Write <code>fib_memo(n)</code> using a dictionary. Check whether a result is saved before expanding the recursive calls. When you compute a new result, save it before returning.</p><div className="activity-note"><strong>Reason about the order.</strong><p>What happens if the lookup comes after the recursive calls? What happens if you return before saving?</p></div><CodeEditor activity="memoization" code={code} onChange={onCode} record={record} onBusyChange={onBusyChange} /></section>
    <section className="activity-section"><p className="eyebrow">Activity 3 · Compare and explain</p><h3>Watch a cache hit</h3><button className="secondary" onClick={() => { setComparison(true); record('memoized_trace_revealed') }} disabled={comparison}>Compare with a memoized trace</button>{comparison && <><CallTree memoized record={record} revealRepeated /><div className="comparison-stats"><div><strong>9</strong><span>Naive calls for fib(4)</span></div><div><strong>7</strong><span>Calls with an initially empty cache</span></div><div><strong>2</strong><span>Calls that reuse a saved result</span></div></div><p className="small muted">A cache hit is still a function call, but it does not expand another branch. In this visualization, base-case results are cached too.</p></>}<AnswerField id="complexity-explanation" label="How does caching change the time complexity? What memory does it use?" value={answers['complexity-explanation']} onChange={onChange} />{String(answers['complexity-explanation'] || '').trim() && <details className="concept-recap"><summary>After your attempt: connect this to dynamic programming</summary><p>There are only n + 1 distinct inputs from 0 through n. Under constant-time dictionary access and unit-cost arithmetic, computing each input once gives O(n) time. The cache and deepest chain of recursive calls each use O(n) space.</p><p>This is <strong>top-down dynamic programming</strong>: start with the requested problem and remember the smaller results. A bottom-up approach starts from the base cases and fills results in order.</p><p>Naive Fibonacci repeats branches and takes exponential time; O(2ⁿ) is a useful upper bound. The optimization changes how often a subproblem is computed, while preserving its answer.</p></details>}</section>
  </>
}
