import { test, expect } from '@playwright/test'

const fib = 'def fib(n):\n    if n < 2:\n        return n\n    return fib(n - 1) + fib(n - 2)\n'
const memo = 'def fib_memo(n):\n    cache = {}\n    def solve(k):\n        if k in cache:\n            return cache[k]\n        cache[k] = k if k < 2 else solve(k - 1) + solve(k - 2)\n        return cache[k]\n    return solve(n)\n'
const stairs = 'def climb_stairs(n):\n    cache = {}\n    def solve(k):\n        if k in cache:\n            return cache[k]\n        cache[k] = 1 if k < 2 else solve(k - 1) + solve(k - 2)\n        return cache[k]\n    return solve(n)\n\nprint(climb_stairs(4))\n'

async function pretest(page) {
  for (const [name, value] of [['self-similar', 0], ['termination', 1], ['trace-baseline', 1], ['cache-baseline', 1]]) await page.locator(`input[name="${name}"][value="${value}"]`).check()
  await page.getByRole('button', { name: 'Submit pre-test & continue' }).click()
}

test('complete study flow, real Python, locked assessments, chat context, and export', async ({ page }, testInfo) => {
  const requests = []
  const exceptions = []
  page.on('pageerror', (error) => exceptions.push(error.message))
  await page.route('**/api/ai/chat', async (route) => {
    requests.push(route.request().postDataJSON())
    await route.fulfill({ json: { reply: 'I can clarify the instructions for this part.' } })
  })
  await page.goto('./#/ai-lesson')
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= document.documentElement.clientWidth)).toBe(true)
  await expect(page.locator('.brand')).toContainText('DYNAMIC LEARNING')
  await expect(page.getByRole('button', { name: 'Submit pre-test & continue' })).toBeDisabled()
  await page.getByRole('button', { name: 'Clarify the instructions', exact: true }).click()
  await expect(page.getByText('I can clarify the instructions for this part.')).toBeVisible()
  expect(requests[0].step_id).toBe('ai-pretest')
  expect(requests[0].learner_context).toBeUndefined()
  await pretest(page)
  await expect(page.getByRole('button', { name: /Pre-test.*min/ })).toBeDisabled()
  await page.getByRole('button', { name: 'Next animation step' }).click()
  await expect(page.getByText('Call stack · 2 frames', { exact: true })).toBeVisible()
  await page.screenshot({ path: testInfo.outputPath('introduction-desktop.png'), fullPage: true })
  await page.locator('#doll-explanation').fill('The solid doll is the base case. Smaller dolls make progress toward it.')
  await page.getByRole('button', { name: 'Start the conversation' }).click()
  await expect(page.getByText('I can clarify the instructions for this part.')).toBeVisible()
  expect(JSON.parse(requests[1].learner_context).baseline.score).toBe(4)
  await page.reload()
  await expect(page.locator('#doll-explanation')).toHaveValue(/solid doll/)
  await page.getByRole('button', { name: 'Save & continue' }).click()

  await page.getByRole('radio', { name: /Fibonacci numbers/ }).check()
  await page.locator('#suitability-reason').fill('It branches into the two preceding inputs.')
  await page.locator('#fib-recurrence').fill('F(0)=0, F(1)=1; F(n)=F(n-1)+F(n-2).')
  await page.locator('#code-fibonacci').fill(fib)
  await page.locator('#code-fibonacci').press('Shift+Tab')
  await expect(page.locator('#code-fibonacci')).not.toBeFocused()
  await page.getByRole('button', { name: 'Run tests', exact: true }).click()
  await expect(page.getByText('All practice checks passed.', { exact: true })).toBeVisible({ timeout: 70000 })
  await page.locator('#fib-prediction').fill('3')
  await page.locator('#stack-prediction').fill('4')
  await page.getByRole('button', { name: 'Explore the call tree' }).click()
  await page.getByRole('button', { name: 'Highlight fib(2) calls' }).first().click()
  await expect(page.getByText('Highlighted: fib(2). 2 calls in this tree.', { exact: true })).toBeVisible()
  await page.locator('#trace-explanation').fill('The root waits for both smaller calls before returning their sum.')
  await page.getByRole('button', { name: 'Save & continue' }).click()

  await page.locator('#repeated-count').fill('2')
  await page.locator('#redundancy-explanation').fill('Identical inputs return the same result.')
  await page.locator('#code-memoization').fill(fib.replaceAll('fib(', 'fib_memo('))
  await page.getByRole('button', { name: 'Run tests', exact: true }).click()
  await expect(page.getByText('There is still repeated work to investigate.', { exact: false })).toBeVisible({ timeout: 70000 })
  await page.locator('#code-memoization').fill(memo)
  await page.getByRole('button', { name: 'Run tests', exact: true }).click()
  await expect(page.getByText('All practice checks passed.', { exact: true })).toBeVisible({ timeout: 15000 })
  await page.getByRole('button', { name: 'Compare with a memoized trace' }).click()
  await expect(page.getByText('Calls that reuse a saved result')).toBeVisible()
  await page.locator('#complexity-explanation').fill('Each distinct input is computed once: O(n) time and O(n) memory.')
  await page.getByRole('button', { name: 'Start the transfer task' }).click()
  await expect(page.getByRole('button', { name: /Build & trace.*min/ })).toBeDisabled()
  await expect(page.getByRole('button', { name: /Optimize.*min/ })).toBeDisabled()
  await page.getByRole('button', { name: 'Clarify the instructions', exact: true }).click()
  await expect(page.getByText('I can clarify the instructions for this part.')).toBeVisible()
  expect(requests.at(-1).step_id).toBe('ai-transfer')
  expect(requests.at(-1).learner_context).toBeUndefined()

  await page.locator('#code-transfer').fill(stairs)
  await page.getByRole('button', { name: 'Run my code', exact: true }).click()
  await expect(page.locator('.program-output')).toHaveText('5', { timeout: 70000 })
  await expect(page.locator('.test-results')).toHaveCount(0)
  await expect(page.getByText('All practice checks passed.', { exact: true })).toHaveCount(0)
  await page.locator('#transfer-recurrence').fill('One way for zero or one stair; sum the two preceding cases.')
  await page.locator('#transfer-cache').fill('Lookup before recursion and store before return.')
  await page.locator('#transfer-complexity').fill('O(n) time and O(n) space for distinct inputs and stack.')
  await page.getByRole('button', { name: 'Submit final assessment' }).click()
  await expect(page.getByRole('heading', { name: 'You made the jump.' })).toBeVisible({ timeout: 70000 })
  await expect(page.getByText('Call-count check: passed', { exact: true })).toBeVisible()
  const downloadEvent = page.waitForEvent('download')
  await page.getByRole('button', { name: 'Download my lesson record' }).click()
  const downloaded = await downloadEvent
  const { readFile } = await import('node:fs/promises')
  const exported = JSON.parse(await readFile(await downloaded.path(), 'utf8'))
  expect(exported.transferSubmitted).toBe(true)
  expect(exported.assessment.passed).toBe(true)
  expect(exported.metrics.unsuccessfulMemoizationRuns).toBe(1)
  expect(exported.conversations).toBeUndefined()
  expect(exported.events.some((event) => event.type === 'transfer_submitted')).toBe(true)
  await page.reload()
  await expect(page.getByRole('heading', { name: 'You made the jump.' })).toBeVisible()
  expect(exceptions).toEqual([])
})

test('mobile tutor remains reachable and control keeps its own activity', async ({ page }, testInfo) => {
  await page.setViewportSize({ width: 390, height: 844 })
  await page.route('**/api/ai/chat', (route) => route.fulfill({ json: { reply: 'Complete the four questions, then press Submit.' } }))
  await page.goto('./#/ai-lesson')
  await page.getByRole('button', { name: 'Clarify the task ↗', exact: true }).click()
  await expect(page.locator('#tutor-message')).toBeVisible()
  await page.locator('#tutor-message').fill('Where do I submit?')
  await page.getByRole('button', { name: /Send message/ }).click()
  await expect(page.getByText('Complete the four questions, then press Submit.')).toBeVisible()
  await page.screenshot({ path: testInfo.outputPath('assessment-mobile.png'), fullPage: true })
  await page.getByRole('button', { name: 'Close tutor', exact: true }).first().click()
  await expect(page.locator('#tutor-message')).toBeHidden()
  await page.goto('./#/control-lesson')
  await expect(page.locator('.brand')).toContainText('DYNAMIC LEARNING')
  await expect(page.locator('#tutor-message')).toHaveCount(0)
  await expect(page.getByText(/factorial/).first()).toBeVisible()
})

test('nonterminating code is stopped without blocking chat, and the worker recovers', async ({ page }) => {
  await page.route('**/api/ai/chat', (route) => route.fulfill({ json: { reply: 'Use Run my code to run the code you wrote.' } }))
  await page.goto('./#/ai-lesson')
  await expect(page.getByRole('heading', { name: 'Your starting point' })).toBeVisible()
  await page.addInitScript(() => {
    const key = 'dynamic-learning:ai:ai-pilot-v1'
    const saved = JSON.parse(sessionStorage.getItem(key))
    Object.assign(saved, { partIndex: 4, completedParts: [0, 1, 2, 3], pretestSubmitted: true, transferStarted: true, baseline: { score: 2, total: 4 } })
    sessionStorage.setItem(key, JSON.stringify(saved))
  })
  await page.reload()
  await expect(page.getByRole('heading', { name: 'A new problem, on your own' })).toBeVisible()
  await page.locator('#code-transfer').fill('while True:\n    pass\n')
  await page.getByRole('button', { name: 'Run my code', exact: true }).click()
  await page.locator('#tutor-message').fill('What does Run my code do?')
  await page.getByRole('button', { name: /Send message/ }).click()
  await expect(page.getByText('Use Run my code to run the code you wrote.')).toBeVisible()
  await expect(page.getByText('This run exceeded 8 seconds and was stopped.', { exact: true })).toBeVisible({ timeout: 70000 })
  await page.locator('#code-transfer').fill('print(42)')
  await page.getByRole('button', { name: 'Run my code', exact: true }).click()
  await expect(page.locator('.program-output')).toHaveText('42', { timeout: 70000 })
  await expect(page.locator('.test-results')).toHaveCount(0)
  await page.locator('#code-transfer').fill('def climb_stairs(:')
  for (const id of ['transfer-recurrence', 'transfer-cache', 'transfer-complexity']) await page.locator(`#${id}`).fill('My submitted explanation.')
  await page.getByRole('button', { name: 'Submit final assessment' }).click()
  await expect(page.getByRole('heading', { name: 'You made the jump.' })).toBeVisible({ timeout: 70000 })
  await expect(page.getByText(/SyntaxError on line 1/)).toBeVisible()
  await expect(page.getByText('0/7', { exact: true })).toBeVisible()
  await expect(page.getByText('Recursive call detected: not assessed', { exact: true })).toBeVisible()
})
